<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * Source: php/trainee-data/Enrollment list/Matabungkay-NHS-SMEPA-2025.pptx
 * (Matabungkay National High School's SMEPA report, school year 2024-2025,
 * MPS Result slides for the 1st/2nd/3rd Grading periods.)
 *
 * The pptx does not break MPS scores down by individual instructor, so
 * `instructor` is seeded as a generic placeholder rather than attributed
 * to a specific real teacher.
 */
class PerformanceSeeder extends Seeder
{
    public function run()
    {
        $this->db->table('performance_by_level')->insertBatch([
            ['school_year' => '2024-2025', 'term' => 1, 'grade_level' => 'Grade 7', 'mps' => 63.5, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 1, 'grade_level' => 'Grade 8', 'mps' => 59.82, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 1, 'grade_level' => 'Grade 9', 'mps' => 65.54, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 1, 'grade_level' => 'Grade 10', 'mps' => 61.7, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 2, 'grade_level' => 'Grade 7', 'mps' => 65.2, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 2, 'grade_level' => 'Grade 8', 'mps' => 62.71, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 2, 'grade_level' => 'Grade 9', 'mps' => 66.69, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 2, 'grade_level' => 'Grade 10', 'mps' => 62.59, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 3, 'grade_level' => 'Grade 7', 'mps' => 72.85, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 3, 'grade_level' => 'Grade 8', 'mps' => 67.47, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 3, 'grade_level' => 'Grade 9', 'mps' => 72.11, 'nds' => null],
            ['school_year' => '2024-2025', 'term' => 3, 'grade_level' => 'Grade 10', 'mps' => 67.13, 'nds' => null],
        ]);

        $this->db->table('performance_by_subject')->insertBatch([
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'English', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 62.1],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Filipino', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 69.56],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Science', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 64.59],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Mathematics', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 47.97],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'AP', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 61.2],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'TLE', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 62.57],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'MAPEH', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 59.62],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'ESP', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 80.35],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'English', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 68.5],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Filipino', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 62.22],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Science', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 37.11],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Mathematics', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 38.17],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'AP', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 72.63],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'TLE', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 71.11],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'MAPEH', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 59.86],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'ESP', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 68.92],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'English', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 71.05],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Filipino', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 54.28],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Science', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 53.86],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Mathematics', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 62.83],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'AP', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 63.8],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'TLE', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 66.12],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'MAPEH', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 72.53],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'ESP', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 79.81],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'English', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 67.9],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Filipino', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 57.88],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Science', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 55.74],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'Mathematics', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 52.19],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'AP', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 66.27],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'TLE', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 68.13],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'MAPEH', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 69.57],
            ['school_year' => '2024-2025', 'term' => 1, 'subject' => 'ESP', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 55.88],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'English', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 64.95],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Filipino', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 65.52],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Science', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 62.39],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Mathematics', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 54.32],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'AP', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 70.21],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'TLE', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 69.88],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'MAPEH', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 52.85],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'ESP', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 81.45],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'English', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 70.53],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Filipino', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 64.88],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Science', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 42.45],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Mathematics', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 51.29],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'AP', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 71.42],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'TLE', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 70.44],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'MAPEH', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 59.48],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'ESP', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 71.21],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'English', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 71.41],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Filipino', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 66.25],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Science', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 63.58],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Mathematics', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 55.9],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'AP', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 59.52],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'TLE', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 67.67],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'MAPEH', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 69.36],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'ESP', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 79.82],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'English', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 67.93],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Filipino', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 64],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Science', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 56.99],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'Mathematics', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 50.44],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'AP', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 66.37],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'TLE', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 64.34],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'MAPEH', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 63.77],
            ['school_year' => '2024-2025', 'term' => 2, 'subject' => 'ESP', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 66.9],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'English', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 68.05],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Filipino', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 81.91],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Science', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 70.56],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Mathematics', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 61.13],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'AP', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 71.94],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'TLE', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 71.28],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'MAPEH', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 65.8],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'ESP', 'grade_level' => 'Grade 7', 'instructor' => 'Subject Teacher', 'mps' => 92.13],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'English', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 74.27],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Filipino', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 61.2],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Science', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 46.02],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Mathematics', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 65.27],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'AP', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 71.42],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'TLE', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 82.24],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'MAPEH', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 72.89],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'ESP', 'grade_level' => 'Grade 8', 'instructor' => 'Subject Teacher', 'mps' => 66.41],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'English', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 71.59],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Filipino', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 74.53],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Science', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 61.12],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Mathematics', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 68.91],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'AP', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 69.9],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'TLE', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 68.13],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'MAPEH', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 78.9],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'ESP', 'grade_level' => 'Grade 9', 'instructor' => 'Subject Teacher', 'mps' => 83.79],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'English', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 70.44],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Filipino', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 72.54],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Science', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 60.28],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'Mathematics', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 51.73],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'AP', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 71.15],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'TLE', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 67.84],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'MAPEH', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 74.76],
            ['school_year' => '2024-2025', 'term' => 3, 'subject' => 'ESP', 'grade_level' => 'Grade 10', 'instructor' => 'Subject Teacher', 'mps' => 68.28],
        ]);
    }
}
